server:
  port: 8082

# H2 Console Connectors #
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/departments
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

weclome:
  message: sometimes I think about you

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/departments
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

weclome:
  message: sometimes I think about you
